[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_token = "CqBx2Ce1MijhXcASX7rsb9knaPhmPe2N5HWYVaQVR8zt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/evgenijzdarkin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/metaplex_token_metadata_program.so"